owncloud/libre-graph-api

.drone.star
README.md
api/openapi-spec/v0.0.yml

This holds the spec for https://github.com/owncloud/ocis/blob/de36293a72dd552ccb37a035926fb2a84b425ad5/docs/adr/0005-api-for-spaces.md
PR https://github.com/owncloud/ocis/pull/1827

add Drives Endpoints

---

.drone.star
api/openapi-spec/v0.0.yaml

- Add Generate and Push to remote repo for `go`

add generate push to remote

---

api/openapi-spec/v0.0.yaml

- Cleanup and remove unneeded attributes
- Change the routes to match the official specs

Update the specs to match the current implementation

---

api/openapi-spec/v0.0.yaml

The POST request on CreateDrive doesn't need an url parameter.
@refs

fix wrong path for the POST request

---

api/openapi-spec/v0.0.yaml

Remove the model composition and repeat the sub-type patterns by adding them.
This breaks DRY but should make the code generation possible at all.

Remove the allOf model composition

---

api/openapi-spec/v0.0.yaml

`/users/{User-ID}`
`/users/`
With a selected set of properties
`/groups/`
`/groups/{Group-ID}`

Add user groups

---

api/openapi-spec/v0.0.yaml

add special folder facet to indicate that this resource is a special drive resource.
https://docs.microsoft.com/en-us/graph/api/resources/specialfolder?view=graph-rest-1.0

add special folder facet

---

api/openapi-spec/v0.0.yaml

Add orderby and listallDrives

---

api/openapi-spec/v0.0.yaml

Signed-off-by: Christian Richter <crichter@owncloud.com>

Bump version to 0.14.3

---

api/openapi-spec/v0.0.yaml

This PR will add the drives objects for the user again

readd drive objects

---

api/openapi-spec/v0.0.yaml

This PR bumps version to 0.15.1

bump version to 0.15.1

---

api/openapi-spec/v0.0.yaml

First part of https://github.com/owncloud/ocis/issues/4327

add personal drive to the user

---

api/openapi-spec/v0.0.yaml

Partial-Fix: https://github.com/owncloud/ocis/issues/4283

Add $expand for memberOf to /me

---

.drone.star
api/openapi-spec/v1.0.yaml
index.html

bump version to v1.0.0

---

api/openapi-spec/v1.0.yaml

add graph endpoints for tags
fixes https://github.com/owncloud/libre-graph-api/issues/59

add tags endpoints

---

api/openapi-spec/v1.0.yaml

Adds the example refs from #62 to the requests.

add examples to tag requests

---

api/openapi-spec/v1.0.yaml

- unused parameters
- better tags
- Add required body fields to the drive entity

clean up unused props and add examples for drives

---

api/openapi-spec/v1.0.yaml

extend the identitySet to contain a group field

add identitySet group property

---

api/openapi-spec/v1.0.yaml

rename grantedTo to grantedToIdentities like https://learn.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0

rename grantedTo to grantedToIdentities

---

api/openapi-spec/v1.0.yaml

This adds the specs for a couple of endpoints which we have implemented in the server but didn't add to the spec yet:
/groups/{groupid}/members
/education/schools/{schoolid}/users
/education/schools/{schoolid}/classes
and
/education/classes/{classid}/members
Closes: #64

Add a few missing endpoints

---

api/openapi-spec/v1.0.yaml

Required to list the space member expirations.

add an expiration date time to the permission schema

---

api/openapi-spec/v1.0.yaml

This adds the missing endpoints for managing teachers for classes.
Fixes https://github.com/owncloud/libre-graph-api/issues/72

Add GET/POST/DELETE for managing teachers for classes.

---

api/openapi-spec/v1.0.yaml

Some clarifications that both, the id and a name property can be used to identify resources and a more unique externalId for classes.

document lookup by name

---

README.md
api/openapi-spec/v1.0.yaml
templates/cpp-qt-client/CMakeLists.txt.mustache

Add the ability to build both static and shared libraries which will ease upstream packaging.
Also a bit more useful README.

Improve the CMakeLists Template

---

api/openapi-spec/v1.0.yaml

Our server implementation now supports filters on appRoleAssignments

Add more users filter examples

---

api/openapi-spec/v1.0.yaml

we should document where giving a name or an id should be possible

Id clarifications

---

api/openapi-spec/v1.0.yaml

Adds the `exportPersonalData` endpoint

Add ExportPersonalData endpoint

---

.drone.star

Without this step orphaned files will stay forever

Clean generated directory before we update it

---

api/openapi-spec/v1.0.yaml

This allows to define a date after which the School resource can be deleted

Add 'terminationDate' property to EducationSchool resource

---

.drone.star

Use major version 7 of the generator to generate PHP, while continuing to use the existing 6.2 generator for the other languages.
We can't always easily move up to new releases of the generator across all languages at the same time. So this gives the flexibility to define a generator version for each language, if needed.
We use major version 7 for PHP because we are just getting started with the generated PHP, so we might as well use the latest release and learn to work with that (or fix that!)

Allow using a different generator version for a language

---

api/openapi-spec/v1.0.yaml

See https://learn.microsoft.com/en-us/graph/api/resources/photo?view=graph-rest-1.0 and https://learn.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0 :shrug:

Add photo facet

---

api/openapi-spec/v1.0.yaml

I really want @dschmidt to work on a music app for ocis ;-)

add audio facet

---

api/openapi-spec/v1.0.yaml

I think this is a simple copy-paste mistake and I hope I found the right description

fix copy paste mistake

---

api/openapi-spec/v1.0.yaml

Adds the preferred language to the api

Ocis 5455 language setting

---

api/openapi-spec/v1.0.yaml

We're using '@libre.graph.weight'

Fix 'weight' attribute name in examples

---

.drone.star

This PR bump openai-generator to bring bug fix changes related to issue: https://github.com/owncloud/libre-graph-api-php/issues/4

bump openai-generator

---

api/openapi-spec/v1.0.yaml

See https://learn.microsoft.com/en-us/graph/api/resources/video?view=graph-rest-1.0 and https://learn.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0 🤷

feat: add video facet

---

api/openapi-spec/v1.0.yaml

extend permission to contain the @Client.Synchronize prop

enhancement: add permission client sync prop

---

.editorconfig
api/openapi-spec/v1.0.yaml

this adds editorconfig to have the same format over the place

fix: unify yaml indent style and add editorconfig

---

.editorconfig
api/openapi-spec/v1.0.yaml

Allows updating of individual drive items, only ui visibility for now, branched off from https://github.com/owncloud/libre-graph-api/pull/170, needs to be merged first

Add Patch drive item endpoint

---

api/openapi-spec/v1.0.yaml

change description: remove access to a drive

---

api/openapi-spec/v1.0.yaml

Currently, permission role id is constant. This PR updates permission role-id.

Update constant permission role id

---

api/openapi-spec/v1.0.yaml

There are no required attributes when updating a user. Also 'mail' is not required attribute.

Fix required attribute handling for user
