- api/openapi-spec/v0.0.yaml
There are bugs in the openapi Generator
https://github.com/OpenAPITools/openapi-generator/issues/6378
https://github.com/OpenAPITools/openapi-generator/issues/2892
- Dont use inline schemas, create a named schema for all props when working with `allOf`
> add workaround for composed types

- api/openapi-spec/v0.0.yaml
> repair operation ids

- api/openapi-spec/v0.0.yaml
- according to https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0 the `nullable` modifier will be removed
> remove nullable because it is deprecated

- api/openapi-spec/v0.0.yaml
related to https://github.com/owncloud/ocis/issues/2661
The space Image will be represented as a driveItem on the drive object.
```json
{
"value": [
{
"id": "string",
"createdBy": {},
"createdDateTime": "2021-11-24T16:39:06.730Z",
"description": "string",
"eTag": "string",
"lastModifiedBy": {},
"lastModifiedDateTime": "2021-11-24T16:39:06.730Z",
"name": "Marketing",
"webUrl": "string",
"createdByUser": {},
"lastModifiedByUser": {},
"driveType": "project",
"owner": {},
"quota": {
"deleted": 0,
"remaining": 0,
"state": "string",
"total": 0,
"used": 0
},
"special": [{
"id": "string",
"createdDateTime": "2021-11-24T16:39:06.730Z",
"description": "string",
"eTag": "string",
"lastModifiedDateTime": "2021-11-24T16:39:06.730Z",
"name": "spaceImage",
"webUrl": "string",
"cTag": "string", …
```
> add space image as driveItem and a trash facet for trash metadata 

- api/openapi-spec/v0.0.yaml
> Add endpoints for managing group membership

- api/openapi-spec/v0.0.yaml
Add permissions to the driveItem. The permissions attribute will contain the information of who has access to the drive.
> introduce permissions to the driveItem

- api/openapi-spec/v0.0.yaml
This PR adds descriptions to some of the properties that previously had none. **work-in-progress**
> [fix/missing-comments] Add missing comments

- .drone.star
Unfortunately we still need to use latest, as the fix from our fork is merged upstream but not released yet.
TODO in follow up PR: Pin version.
FIXES: https://github.com/owncloud/libre-graph-api/issues/30
> Switch back to upstream openapi-generator

- api/openapi-spec/v0.0.yaml
- Add the remoteItem type to also represent the grant on the share owners storage.
> add remote item for shares

- api/openapi-spec/v0.0.yaml
To trigger a release of the "sub-projects" after recreating the LICENSE
files.
> Bump version to v1.14.1

- .drone.star
to avoid deleting e.g. LICENSE files in the target repos
> remove the clean-* steps

- api/openapi-spec/v0.0.yaml
LICENSE was still being	removed in target repos. Should be fixed with
latest change in .drone.star
> Bump version to v1.14.2

- api/openapi-spec/v0.0.yaml
This PR adds the `memberOf` field to the /users endpoint.
> Add memberOf field to /users endpoint

- api/openapi-spec/v1.0.yaml
/drives/{drive-id}/root missed drive-id parameter
/education/schools/{school-id}/classes/{class-id}/$ref missed class-id parameter
> fix drive-id and class-id parameters

- api/openapi-spec/v1.0.yaml
Add bearer auth to education requests.
- OpenIDConnect stays the "global" auth mechanism
- Bearer Auth is possible only on the marked requests
> Add bearer auth to edu requests

- api/openapi-spec/v1.0.yaml
Add a minimum viable implementation of the msgraph [appRoleAssignment](https://learn.microsoft.com/en-us/graph/api/resources/approleassignment?view=graph-rest-1.0) to assign roles to users per school:
principalId: The id of the user to whom you are assigning the app role.
resourceId: The id of the resource [servicePrincipal](https://learn.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta) that has defined the app role.
appRoleId: The id of the [appRole](https://learn.microsoft.com/en-us/graph/api/resources/approle?view=graph-rest-beta) (defined on the resource service principal) to assign to the user.
> Add app roles and assignments

- api/openapi-spec/v1.0.yaml
graph always uses the plural form
> fix /applications endpoint

- .drone.star
We now pin the image to the SHA for the 6.2.0 release. To get away from the pre-release snapshot we've been using for a while now.
Closes: #38
As far as I could see this doesn't introduce any problematic changes to the libraries that we are generating from this.
> Bump openapi-generator to v6.2.0

- api/openapi-spec/v1.0.yaml
Not sure how that ended up in our spec but we're not using them currently and the graph api mandates createdBy and lastModifiedBy instead.
Closes: #25
> Remove redundant and unused 'createdByUser' and 'lastModifiedByUser'

- .drone.star
To avoid publishing code that doesn't validate. Also run the generated code through gofmt.
> Run the validate step before publish, add gofmt to validate

- api/openapi-spec/v1.0.yaml
when using `$expand` the user struct needs to have an `appRoleAssignments` property that can be populated
> add appRoleAssignments to user

- api/openapi-spec/v1.0.yaml
We currently don't use onPremisesDomainName and onPremisesSamAccountName anywhere.
Closes: #71
> Remove unused attributes from groups and educationClass

- api/openapi-spec/v1.0.yaml
This adds some specific examples for supported $filters on the /users endpoint.
Also cleans up quite a few currently unsupported query parameters on different endpoints.
> Add examples for $filter on /users

- api/openapi-spec/v1.0.yaml
We'll be using this to indicate groups as being "ReadOnly". That is groups, coming from some external system which we can't update.
> Add "groupTypes" property to the group resource

- templates/cpp-qt-client/CMakeLists.txt.mustache
Depends on https://github.com/owncloud/libre-graph-api/pull/103
@dragotin this will prefer Qt6, from your perspective as a packager, should I add an option to force Qt6 and assume 5 otherwise?
> Qt6 support

- .drone.star
- .gitignore
- README.md
- composer.json
Add generated PHP for the libre-graph-api.
I used `php-parallel-lint` to verify that the generated PHP is valid syntax. The pipelines for other languages do similar linting. I suppose that is all that we can really do to get a "warm and fuzzy" that something was generated.
> Add libre-graph-api-php

- templates/php/model_generic.mustache
Add a template to fix an invalid PHP call (preg_match receives a DateTime object) see details in https://github.com/OpenAPITools/openapi-generator/pull/16513 
This fix is only temporary and should be removed when the next version of the generator is released
> convert data to string before giving it to preg_match

- api/openapi-spec/v1.0.yaml
This is a prerequisite for [sharing NG](https://github.com/owncloud/libre-graph-api/pull/112) to clarify roles and permissions management.
Permissions are represented as a list of resource actions and conditions that must be met for the action to be allowed.
Resource actions are a set of tasks that can be performed on a resource.
The following is the schema for resource actions:
```
{Namespace}/{Entity}/{PropertySet}/{Action}
```
For example: `libre.graph/applications/credentials/update`
* *{Namespace}* - The services that exposes the task. For example, all tasks in libre graph use the namespace `libre.graph`.
* *{Entity}* - The logical features or components exposed by the service in libre graph. For example, `applications`, `servicePrincipals`, or `groups`.
* *{PropertySet}* - Optional. …
> add role management

- api/openapi-spec/v1.0.yaml
libregraph API spec for the sharing ADR in https://github.com/owncloud/ocis/pull/6995
When following a share lifecycle, the following OCS requests can be replaced with these libregraph counterparts:
**OCS**: web calls two endpoints:
- `/ocs/v1.php/apps/files_sharing/api/v1/shares?path={space-relative-path}&space_ref={space-id}&reshares=true`
- `/ocs/v1.php/apps/files_sharing/api/v1/shares?path={space-relative-path}&space_ref={space-id}&shared_with_me=true`
**ms graph**: `/drives/{drive-id}/items/{drive-item-id}/permissions`
```json
{
"value": [
{
"id": "collaborative-share-id",
"roles": [
"write"
],
"grantedToV2": {
"user": {
"displayName": "Albert Einstein",
"id": "4c510ada-c86b-4815-8820-42cdf82c3d51"
}
},
},
{
"id": "public-link-share-id",
"roles": [
"read"
],
"link": {
"webUrl": …
```
> [WIP] add Sharing NG endpoints

- api/openapi-spec/v1.0.yaml
See https://learn.microsoft.com/en-us/graph/api/resources/geocoordinates?view=graph-rest-1.0 and https://learn.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0 🤷🏻 
Tika extracts these properties at least from images.
> Add location facet

- .drone.star
I would like to use the generated `ToMap` function of models (in go) which has been added after v6.2.0
`openapi-generator:7.0.x` introduces breaking changes in the go code. 
1) required go version is bumped from 1.17 to 1.18
2) I needed to make these adjustments in the oCIS code base:
```diff
diff --git a/services/proxy/pkg/user/backend/cs3.go b/services/proxy/pkg/user/backend/cs3.go
index 70cb9cb8a4..aea2d4cebf 100644
--- a/services/proxy/pkg/user/backend/cs3.go
+++ b/services/proxy/pkg/user/backend/cs3.go
@@ -175,7 +175,7 @@ func (c *cs3backend) CreateUserFromClaims(ctx context.Context, claims map[string
return nil, fmt.Errorf("Error creating user from claims: %w", err)
}
-       req := lgClient.UsersApi.CreateUser(newctx).User(newUser)
+       req := …
```
> Bump openapi-generator to v7.0.1

- .drone.star
We stayed on 6.6.0 to avoid a breaking change, but apparently the breaking change (Api -> API in generated struct names) seems to have been introduced before 7 already. So after a quick discussion we decided to accept this breaking change.
> Switch go to openapi-generator 7

- api/openapi-spec/v1.0.yaml
This allows us to add the version to the 'path' components so that we can make specific paths only available for a certain version.
As agreeed, this is also moving the sharing and role management related endpoints to the v1beta1 version.
Note: This might require client side changes I haven't checked that yet.
> Remove version from base URLs make sharing NG endpoints beta

- api/openapi-spec/v1.0.yaml
1. We need to extend https://learn.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-1.0&tabs=http to use the quick link feature which is already implemented in the OCS Api.
Therefore we add `@libre.graph.quickLink` as a `bool` value to the createLink and the sharinLink objects.
2. We need to extend https://learn.microsoft.com/en-us/graph/api/resources/sharinglink?view=graph-rest-1.0 to use the internal link feature which is already implemented in the OCS Api.
Therefore we add the "internal" sharing link type which has no share permissions.
Relates to https://github.com/owncloud/ocis/issues/6993
> feat(api): Add link type internal and quicklink properties

- api/openapi-spec/v1.0.yaml
In ocis we allow more than one link per resource. As a consequence we need a dedicated call to set a  password on an existing link.
Relates to https://github.com/owncloud/libre-graph-api/issues/136
> feat(api): Add missing setPassword endpoint to sharing NG

- api/openapi-spec/v1.0.yaml
According to the description this should get the users and not the classes.
Partly explains / fixes https://github.com/OpenAPITools/openapi-generator/issues/17143
> retrieve users not classes by 'schools/{school-id}/users'

- api/openapi-spec/v1.0.yaml
We need to return a collection of permissions
Fixes: #138
> Fix response type for POST '/v1beta1/drives/{drive-id}/items/{item-id}/invite'

- api/openapi-spec/v1.0.yaml
In order to "unset" an expiration date, we need a nullable dateTime type.
> fix(api): Make the expiration date nullable

- templates/php-nextgen/api.mustache
Apply the fix of https://github.com/OpenAPITools/openapi-generator/pull/17120 in the local template.
Sadly we cannot delete the template yet because https://github.com/OpenAPITools/openapi-generator/issues/17113 is not fixed yet.
This should finally fix https://github.com/owncloud/libre-graph-api-php/issues/4
> apply json decode fix in local php template

- api/openapi-spec/v1.0.yaml
the remoteItem had no permissions list which is needed for `shared by me`
> enhancement: extend remoteItem to contain permissions

- api/openapi-spec/v1.0.yaml
This adds the necessary endpoints for mounting and unmounting shares.
Since the endpoints could be implemented for all drives I left the `{drive-id}` parameter in. The server implementation can check if it is the share jail id and return a not implemented error for all other drives.
Mounting happens by POSTing a new driveItem to the root children collection:
```http
POST /v1beta1/drives/a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668/root/children
ContentType: application/json
{
"name": "Einsteins project share",
"remoteItem": {
"id": "a-storage-provider-id$a-space-id!a-node-id",
"permissions": [
{
"id": "share-id"
}
]
}
}
```
The necessary ids can be taken from the output of the `/me/drives/sharedWithMe` endpoint
Unmounting happens by DELETEing the driveItem in …
> add mount and unmount example

- api/openapi-spec/v1.0.yaml
the openapi validator [spits warnings](https://drone.owncloud.com/owncloud/libre-graph-api/528/1/2): 
```
docker.io/openapitools/openapi-generator-cli@sha256:1894bae95de139bd81b6fc2ba8d2e423a2bf1b0266518d175bd26218fe42a89b: Pulling from openapitools/openapi-generator-cli
Digest: sha256:1894bae95de139bd81b6fc2ba8d2e423a2bf1b0266518d175bd26218fe42a89b
Status: Downloaded newer image for openapitools/openapi-generator-cli@sha256:1894bae95de139bd81b6fc2ba8d2e423a2bf1b0266518d175bd26218fe42a89b
+ /usr/local/bin/docker-entrypoint.sh validate -i api/openapi-spec/v1.0.yaml
Validating spec (api/openapi-spec/v1.0.yaml)
Warnings: 
- Unused model: directoryObject
- Unused model: educationOrganization
- Unused model: entity
[info] Spec has 3 recommendation(s).
```
> remove unused schemas

- api/openapi-spec/v1.0.yaml
- Move the `UI.Hidden` and `client.synchronize` flags to the outer drive item
- add `invitation` property to `permissions`  (to expose the share creator)
- remove `shared` property from `remoteItem`. With the share creator information move to `permssion` this can go away.
- adjust examples accordingly
> Adapt shareWithMe specifcation to be able to group shares by shared resource

- api/openapi-spec/v1.0.yaml
We don't need a permission id. Just the id of the remoteItem is enough.
> Fix share mounting example

- api/openapi-spec/v1.0.yaml
See
https://learn.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0
https://learn.microsoft.com/en-us/graph/api/resources/thumbnailset?view=graph-rest-1.0
https://learn.microsoft.com/en-us/graph/api/resources/thumbnail?view=graph-rest-1.0
Tbh I'm not sure about the `thumbnailSet` definition, while I copied the exact definition from the `thumbnailSet` documentation - this page https://learn.microsoft.com/en-us/graph/api/driveitem-list-thumbnails?view=graph-rest-1.0&tabs=http#size-options lists more options and they are partially contradicting (at least the large thumbnail is said to be 1920x1920 or 800 longest on the other page)
> Add thumbnails relationship to driveItem

- api/openapi-spec/v1.0.yaml
This adds a couple of new enpdoints for being able to access a drive's root more easily.
Related: https://github.com/owncloud/ocis/issues/8351
> Add shortcut paths for drive root item

- api/openapi-spec/v1.0.yaml
The "Share invite" function lacks the necessary @libre.graph.recipient.type body parameter, which is essential for a successful API request to share invites.
Fixes 
- https://github.com/owncloud/libre-graph-api/issues/169
> Add missing body parameter on share invite

- api/openapi-spec/v1.0.yaml
the update drive item endpoint now returns the updated drive item
> fix: return a drive item after the drive item update

- api/openapi-spec/v1.0.yaml
Documents the endpoint for getting drive items via ID as implemented via https://github.com/owncloud/ocis/pull/8939/commits/ad016b1fc4fbd0e033c7f1bff4e8dfc2f02e4a79.
> feat: add documentation for drive items GET endpoint

- api/openapi-spec/v1.0.yaml
the c-time is not part of the official ms spec, that means were extending the permission object with a creationDateTime object property.
not sure how we proceed with that (not part of the official spec), lets discuss it here!
Needed by: https://github.com/owncloud/ocis/issues/8749
> enhancement: add creation time to the permission object

- .drone.star
golang to 1.22
openapi-generator to 7.6.0
> chore: Bump container image releases

- api/openapi-spec/v1.0.yaml
We still support basic auth and without this in the spec the generated go client will not include support for it.
> Add Basic auth to the supported security schemes

- api/openapi-spec/v1.0.yaml
The UpdateDrive request does not require the 'name' property. It is only required for creating a drive. We fixed this by introducing a new type 'driveUpdate' with 'name' as an optional property and deriving the 'drive' type from it with 'name' as a required property.
This is needed because the latest release of the code generator for go now does some basic validation for required attributes.
> Fix request body for UpdateDrive

- README.md
- api/openapi-spec/v1.0.yaml
This is just a tidy up of things that, IMO, have no syntactic impact (i.e. won't break backward-compatibility of any use of this API.
> chore: fix typos in comments, descriptions and summaries

- api/openapi-spec/v1.0.yaml
One of the education user properties is `primaryRole` (not `primariyRole`)
> chore: fix primaryRole spelling in examples

- api/openapi-spec/v1.0.yaml
This is needed for "OCM" integration in ocis. To be able to differentiate user's accepted via OCM from normal member users.
> Add "Federated" as a new user type

- api/openapi-spec/v1.0.yaml
part of https://github.com/owncloud/ocis/issues/9745 and https://github.com/owncloud/ocis/pull/9765
> add permissions $filter and $select

- api/openapi-spec/v1.0.yaml
We don't want 'userType' to be set on POST/PATCH requests for now. Currenly users with a type different from 'Member' are created either via ocm or via graph invite requests.
See: https://github.com/owncloud/ocis/issues/9858 for details
Also 'memberOf' is a read-only relation in MS Graph.
> Mark user properties `userType` and `memberOf` as read-only

- api/openapi-spec/v1.0.yaml
Current plan is to only provide the `lastSuccessfulSignInDateTime` property.
Needed for: https://github.com/owncloud/enterprise/issues/6726
> Add 'signinActivity' to user
